### ISSUE TITLE
Support Query Hints

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel_impala#39]
We might need to take advantage of query hints in Impala to improve the performance of some of our queries.

[This page describes the kinds of query hints you can apply in Impala](https://www.cloudera.com/documentation/enterprise/5-12-x/topics/impala_hints.html#hints) and we need to implement the BROADCAST and SHUFFLE hints for JOINs.  We don't (yet) need the insert ... select hints to be implemented.

Please note that it looks like the SELECT part of the statement must also change to include the STRAIGHT_JOIN hint in order to enforce the JOIN query hints.  Though it seems this can be an optional part of the query hints, I am ok with always including STRAIGHT_JOIN in the SELECT statement if a hint is provided for the JOIN.

**Comment by jeremyevans** [comment]
I'll try to work on this and #40 next Tuesday evening.  Unfortunately, I'm currently out of the country at a conference and won't be able to work on this until I return.

**Comment by aguynamedryan** [comment]
Thanks, @jeremyevans. No rush!  Have fun at your conference!
