### ISSUE TITLE
Fix up SEMI JOIN support

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel_impala#43]
I implemented a hack for SEMI JOIN in these two commits:
- f9533362d1ee3117d28fdbcac6741711bbaae591
- f71c4df245e1182000eab4fb03d044e2a188a73c

But I hope there's a nicer way to implement this feature, so please refactor it if warranted.

Here's the Impala documentation if required:
https://impala.apache.org/docs/build/html/topics/impala_joins.html

**Comment by jenniferduryea** [comment]
per @aguynamedryan this is done and tested.
