### ISSUE TITLE
LIKE option for Impala#tables

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel_impala#44]
Impala supports a LIKE statement for SHOW TABLES: https://impala.apache.org/docs/build/html/topics/impala_show.html

I'd like to allow this option to be passed into #tables so that we can widdle down the number of tables returned by Impala since we then have to call `describe table` on each to determine if it truly is a table.

I imagine the call would look like: `db.tables(schema: :jigsaw_temp, like: "*this*|*that*")`

**Comment by jenniferduryea** [comment]
Per @aguynamedryan this is done and tested.
